function [test, train] = splitTestTrain(data, N)
%SPLITTESTTRAIN given the data struct this splits into train and test
%samples by taking the first N samples for the test set!

assert(N < length(data.trainImages));

test = struct('trainImages', {data.trainImages(1:N)},...
    'trainBoxes', data.trainBoxes(:, 1:N),...
    'trainBoxImages', {data.trainBoxImages(1:N)},...
    'trainBoxPatches', data.trainBoxPatches(:, :, :, 1:N));
train = struct('trainImages', {data.trainImages(N+1:end)},...
    'trainBoxes', data.trainBoxes(:, N+1:end),...
    'trainBoxImages', {data.trainBoxImages(N+1:end)},...
    'trainBoxPatches', data.trainBoxPatches(:, :, :, N+1:end));
end

